# Generated by Django 3.2.7 on 2021-09-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210915_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsExperience',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('thumbnail', models.TextField(blank=True, db_column='Thumbnail', null=True)),
            ],
            options={
                'db_table': 'accounts_experience',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountsProject',
            fields=[
                ('id', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('thumbnail', models.TextField(blank=True, db_column='Thumbnail', null=True)),
            ],
            options={
                'db_table': 'accounts_project',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
