# Generated by Django 3.2.7 on 2021-09-30 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210930_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountsexperience',
            options={},
        ),
        migrations.AlterModelOptions(
            name='accountsproject',
            options={},
        ),
    ]
